name: Build site daily

on:
  schedule:
    - cron: "0 6 * * *"   # rulează zilnic la 06:00 UTC (~09:00 România)
  workflow_dispatch:       # poți rula manual din Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Generate index.html
        env:
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python fetch.py

      - name: Commit updated site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Auto-update site" || echo "No changes"
          git push
